name: plm
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - numpy>=1.22,<1.25
  - pandas
  - pytorch
  - cudatoolkit
  - pathlib
  - biopython
  - pip
  - pip:
    - ankh
    - fair-esm
    - jax-unirep
    - transformers
    - tensorboard